### PR TITLE
Adding IQFeed Interface, builder for Candle in univocity-trader-core

### PR DESCRIPTION
**Pull request by jecker7**
Interface to retrieve historical prices from IQFeed w/ websocket connection and API-specific requests

### CODE REVIEW

**Comment by jbax** [comment]
Thanks a lot for your contribution!! I'll try merge it all today. Do you mind writing a quick usage guide in a `README.md` to the root of this `univocity-trader-IQFeed` subproject?

**Comment by jecker7** [comment]
Sure thing, will be making a lot of changes in next few days.

**Comment by jbax** [comment]
Almost all changes merged manually, thanks a lot. I made a few adjustments and did not introduce the candle builder as it's not used anywhere.

Creating a simulator or live trader is exactly as you'd do with Binance (see updated tutorial for reference):

```
	IQFeed.Simulator simulator = IQFeed.simulator();
	Account account = simulator.configure().account();
		
	simulator.run();
```

Thanks again!

**Comment by jecker7** [comment]
Is there any way I can still be added to contributor list for my contribution? Or does manual merge negate this?

**Comment by jbax** [comment]
Yes the commit I did won't have your user associated with them. I didn't
realize that, sorry.

The only solution I can think to make you appear in the "blame" list on
github is to delete the iqfeed subproject. Then you can submit a PR that
reverts my commit and puts it all back. Dirty but will work.

Alternatively you can submit a simple PR which adds the javadoc tag
`@author` plus your name or email to the files in the iqfeed subproject.

Feel free to also add yourself to the <authors> section of the pom.xml as
well.

I changed the repository rules to only allow squashed PRs (all changes in a
PR come as a single commit) because merging all individual changes was
being time consuming and painful. This will prevent having to manually copy
changes from large PRs.

**Comment by jecker7** [comment]
Alright, I'll delete the module and make another squashed commit for the whole project after some additional work and more complete testing, needs more changes anyway. 
Thanks for the tips.

**Pull request closed without merging**
