### PR TITLE
currencies

### PR DESCRIPTION
**Pull request by teverett**
Addition of a class which contains currencieas, both fiat and crypto. To be used later.

### CODE REVIEW

**Comment by jbax** [comment]
Not sure why we'd need this as the exchanges give the symbols available
dynamically.

Should be OK if the intention is to display this in a UI later on. But use
univocity-parsers ;-) for processing the CSV and expand our little monopoly

**Comment by teverett** [comment]
I laughed.  :)

**Comment by jbax** [comment]
Don't need to close this one unless you think there is no utility for it.

**Comment by jbax** [comment]
Reopening as the changes are mostly OK. I'll update to use univocity-parsers

**Pull request merged**
